#!/usr/bin/python3
import calendar 
import datetime
import dbus
import os
import os.path
import sys
import yaml

projects = yaml.load(open(os.environ['HOME'] + '/.config/hamster-projects.yaml'))

def mapping(title, path):
    pathes = (os.path.dirname(path).split('/'))
    pathes.append(title)

    for name in reversed(pathes):
        try:
            return projects[name.lower()]
        except KeyError:
            pass

    return "organize@Daily"

def main(argv=sys.argv):
    if(not argv[2:]):
        print("%s: page text" % argv[0])
        return
    title = os.path.splitext(os.path.basename(argv[1]))[0]

    activity = mapping(title, argv[1])
    description = argv[2]
    if(activity != title):
        description = "%s - %s" % (title, description)
    hamster = dbus.SessionBus().get_object('org.gnome.Hamster', '/org/gnome/Hamster')
    hamster.AddFact('%s,%s' % (activity, description), calendar.timegm(datetime.datetime.now().timetuple()), 0, False)

if __name__ == "__main__":
    # /home/chihchun/workspace/zim/zim_custom_tools/hamster-zim %s %t
    # %s real page source
    # %t selected text
    main()
