#!/usr/bin/python3
import calendar 
import datetime
import dbus
import os
import os.path
import sys
import yaml



def mapping(path):
    projects = yaml.load(open(os.environ['HOME'] + '/.config/hamster-projects.yaml'), Loader=yaml.BaseLoader)

    pathes = (os.path.dirname(path).split('/'))
    print(projects)
    print(pathes)
    for name in reversed(pathes):
        name = name.lower()
        if name in projects:
            return projects[name]
    
    for path in reversed(pathes):
        for name in path.split('_'):
            name = name.lower()
            print (name)
            if name in projects:
                return projects[name]

    return "Zone Out@Personal"

if __name__ == "__main__":
    # /home/chihchun/workspace/zim/hamster-scripts/hamster-zim %s %t
    # %s real page source
    # %t selected text

    argv=sys.argv
    if(not argv[2:]):
        print("%s: page text" % argv[0])
        raise Exception("hamster-zim %s %t")
    activity = mapping(argv[1])
    description = argv[2]

    hamster = dbus.SessionBus().get_object('org.gnome.Hamster', '/org/gnome/Hamster')
    hamster.AddFact('%s,, %s' % (activity, description), calendar.timegm(datetime.datetime.now().timetuple()), 0, False)